### ISSUE TITLE
What happened to the dracula theme

### ISSUE THREAD

**Issue by eleanor-clifford** [cuspaceflight/novus#2]
What? How can you do this?! This is outrageous! It's unfair! How can you be using matplotlib and not use dracula?!

**Comment by henryefranks** [comment]
Funny story on that. I replaced all the old code with the v6.1 code, which doesn't have dracula theming included yet. You can sleep soundly tonight in the knowledge that I've already added it to my refactor, which I haven't pushed yet.

**Comment by eleanor-clifford** [comment]
My faith in humanity has been restored.

**Comment by henryefranks** [comment]
I've pushed up the start of my big refactor which includes, most notably, restoration of the dracula theme to matplotlib. 🎉

**Comment by eleanor-clifford** [comment]
Thanks, that was obviously the most important part of the codebase
